### ISSUE TITLE
problems with running buildpe on USB drive formatted to fat32 but seems to work with ntsf

### ISSUE THREAD

**Issue by jame137** [unixabg/SteadierState#3]

**Comment by unixabg** [comment]
Greetings,
It appears that the buildpe.cmd operates with both fat32 and ntfs usb drives. After running the buildpe.cmd the usb drive created is in fact fat32, whether you started with ntfs or fat32 on the usb drive. I have been unable to produce any error on usb drives which are correctly formatted. Closing issue.
